### ISSUE TITLE
concept map integration

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#15]
Thoughts from @tracykteal on integrating concept map exercise with the rest of the curriculum:

"In performance revisited I added in the concept maps

"
Performance revisited 
 
Tracy demonstrated how to go from a Data Carpentry lesson to a concept map and all the way to a “I, we, you” teaching sequence. Picked the Data Carpentry R ecology lesson section on filter and select. Drew a concept map that would show how I prepared to teach the concept. Talked about the I, We, You model that meant I was teaching one concept as a time (recognizing limitations of memory and mental models) and giving learners a chance to participate. Went through teaching that section showing I, We, You and asking for feedback. Got through to the challenge and just said that the instructor would have the learners do the challenge. Tried to link together the things learned today - concept maps, memory, formative assessment (challenges), getting feedback from learners as we teach, during we, teaching as a performance art. "

**Comment by raynamharris** [comment]
I like the idea of revamping the concept map portion. For one, I've noticed that many students come prepared to teach python for loops, so it is difficult for them to create a unique concept on their own since the instructor just walked through a python for loop. 

I like the idea of walking the students through a much larger concept map (say R ecology) and then focusing on s small piece of the concept map for teaching (filter and select) because this ties in better to the story that we convey about recognizing the limits of short-term memory. 

Someone still might have by chance chosen to teach filter and select, but their hand-drawn mental model will look different that the one presented by the training because the trainers has big and broad (focused on the whole lesson) while the learner will draw a map that is narrowly focuses on episode.

**Comment by ErinBecker** [comment]
I think this is addressed with the way the concept map exercise is presented now in https://github.com/ErinBecker/instructor-training-reorg/pull/162. @raynamharris @tracykteal - ok to close this issue?

**Comment by raynamharris** [comment]
I think this new order is much improved over the old order. Okay to close.
