### ISSUE TITLE
update introduction to mental models

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#21]
In 02-practice.md, the example given for "mental model" is limited to a small, specific example (ball and stick atomic model). Mental models are generally large, complex models of entire areas or domains. How can we update the example given here to more accurately reflect what a mental model is? This should also help learners understand the references we make throughout the rest of this section to mental model connectivity.

**Comment by raynamharris** [comment]
@maneesha did a great job explaining mental models in our workshop today. She included another example of a model of the solar system made with styrofoam balls that was very compelling.

**Comment by maneesha** [comment]
Thanks @raynamharris !  I went with the solar system model because we were with space science people.  It may have been more compelling to this group but wasn't necessarily more complex than using the atom model.  Many of us may have built  (or seen) a model of the solar system of styrofoam balls - and that's enough for most people.  Astronomers know that there is much more to that.

To illustrate a broken mental model I also gave an elementary school teaching example since a lot of my background is in K-12 teaching.  When teaching elementary school kids about heat and energy they will often think that a blanket *makes* things warm.  That comes from personal experience.  Kids know if you're cold and get under a blanket, you get warm. We want to teach kids that happens because the blanket insulates your body heat, not because the blanket generates heat.  We do so through gathering scientific evidence - putting a thermometer under a blanket with nothing else and seeing the temperature does not change.

**Comment by raynamharris** [comment]
Ah yes, the blanket example was really good too. :)

I think the solar system model will be more compelling to anyone not in STEM. So many people despise chemistry that I think some of our future instructors might not really be familiar with a ball and stick model. (I was a chemistry major, so I drew them all the time, but I'm weird). The solar system is something we learn as kids. Also, I like that the styrofoam balls are 3D models whereas the ball and stick is open only a 2D model.

**Comment by karenword** [comment]
Can we generate a mental model that is specifically relevant to software/data management?  These types of models are more abstract, but we want our students to apply them in this way, yes? How about file system navigation -- "where" things are located on a computer. What does a broken mental model of this look like? I find that I don't get very far with mental models without referring to concept maps, and vice versa. Should these be more explicitly connected?

**Comment by ErinBecker** [comment]
Closed with #158
