### ISSUE TITLE
Reflective practice

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#3]
Add section on the importance of reflective practice and how we implement this in the classroom to 02-practice.md.

**Comment by raynamharris** [comment]
Currently, the episode on practice ([2-practice.md](https://erinbecker.github.io/instructor-training-reorg/02-practice/)) is all about mental models. 

I was thinking that the episode on "teaching as a performance art" ([11-performance](https://erinbecker.github.io/instructor-training-reorg/11-performance/)) should be renamed reflective practice, because this is the one where have student give and receive feedback. 

Is that the plan for this section?

**Comment by ErinBecker** [comment]
Thanks @raynamharris - really good comments, and yes, I've had this issue before when trying to talk about teaching instructors. It's hard to keep terminology unambiguous so that it's always clear when we're talking about something the learners (people in SWC/DC workshops) should be doing, and something the trainees (people in instructor training workshops) should be doing. 

We're really talking about two sides of the same coin:
- Learners need reflective practice on their coding while they're going through the lessons in order to integrate concepts into long-term memory. 
- Instructors/Trainees need reflective practice on their teaching in order to build muscle memory (e.g. for live coding) and make these teaching practices part of their long-term habits.

Any ideas how we can name these two episodes to disambiguate this?

**Comment by ErinBecker** [comment]
Actually, what about making this connection explicit by naming the episodes:

"How Learning Works: The Importance of Practice" and
"Building Teaching Skill: The Importance of Practice" ?
