### ISSUE TITLE
Formative assessment and Carpentries

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#4]
Add section describing how the Carpentries use formative assessment during workshops and why we do it this way to 02-practice.md.

**Comment by karenword** [comment]
Also while the text states that "Instructors should use MCQs or some other kind of formative assessment at least every 10-15 minutes in order to make sure that the class is actually learning." I find that this point is often lost (probably because they are not included with this kind of frequency for most lessons). I've used formative assessment to emphasize! "How often do you think you ought to use these types of assessments when you teach, ideally?" This sets up a contrast with the status quo, so I'm not sure if this meshes well with the intent here or not.

**Comment by ErinBecker** [comment]
I agree with @karenword that this emphasis is often lost and I don't see this frequency at the workshops I've attended. I think this has something to do with folks not recognizing the variety of "formative assessments" that can be used. I had one trainee mention to me that we weren't doing much formative assessment, thinking that only MCQs counted, but we had been doing lots of "type your answers into the etherpad" and think-pair-share types of formative assessment. Maybe we could add an exercise early on for the trainees to note the frequency and types of formative assessments that are done in training.

**Comment by DanielleQuinn** [comment]
I agree; it seems that in the Assessing Mental Models section, the focus is on using MCQs as a means of formative assessment but it is not made clear that this is just one of many methods that could be used. This could either be explicitly stated or incorporated into the exercise by adding an extra piece: (a) What other methods of formative assessment (i.e. guided practice) could be used? (b) How many times has formative assessment been used since the start of this workshop? (c) Give one example and the purpose the assessment served.

**Comment by ErinBecker** [comment]
@DanielleQuinn I love this idea. Would you like to put in a PR?

**Comment by ErinBecker** [comment]
Closed with https://github.com/ErinBecker/instructor-training-reorg/pull/158/files
