### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#40]
Why is _extras/figures.md necessary? It doesn't appear to be automatically updated when new figures are added to the episodes and so it's out of date. Can we get rid of this file or is it needed?

**Comment by raynamharris** [comment]
There are two issues here. Unfortunately, it does appear that the [_extras/figures.md](https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_extras/figures.md) file is broken because the figures are not automatically updated. 

However, when this file works, it gives the instructor the ability to provide a clean weblink that they can provide the students to view the figure. Without this file, instructor has to either show the whole webpage or they have to show a link to the file on github, which is a little cluttered.

**Comment by raynamharris** [comment]
When this file was working, it was a handy feature. However (given that 1) you can click the image in the lesson to get its hyperlink and 2) that the feature is broken and does not automatically update) I am in favor of deleted this page.

**Comment by ErinBecker** [comment]
Added to checklist and closing here.
