### ISSUE TITLE
What costs what?

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#46]
In [episode 22](https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_episodes/22-carpentries.md) there is a small section about the costs of running workshops. 

I'm not convinced that this information is update (i.e. it doesn't say anything about costs differences for partner institutions and non-partner institutions), and I'm not convinced that this information should be in the curricula either. 

Can we replace this entire section with a link to a document that is stored elsewhere, again maybe in https://github.com/carpentries/policies. 

Finally, (whether we keep this here or move it) I think this information could be more easily absorbed if it were in the form of a table.

**Comment by ErinBecker** [comment]
Agreed on all counts. This information should be on the joint Carpentries website and tabulated for ease of digestions.

**Comment by ErinBecker** [comment]
Added to checklist and closing here.

**Comment by ErinBecker** [comment]
@weaverbel is putting together a joint Carpentries webpage, which will be the place we'd like to reference back to in this case. Since it's not up yet, I propose we leave these materials in the lesson proper for this release (and check them to make sure they're accurate!) and then remove them and reference to the joint Carpentries page when it's up.

**Comment by ErinBecker** [comment]
It looks like this was already taken care of very elegantly (by @raynamharris?) in a previous PR that I didn't notice when I wrote my last comment. The materials now reference back to the SWC and DC websites rather than listing fee information independently.
