### ISSUE TITLE
Wrap-up episodes don't address 'What have we learned?'

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#50]
All four of the wrap-up (Day [1 AM](https://erinbecker.github.io/instructor-training-reorg/06-summarize/) , [1 PM](https://erinbecker.github.io/instructor-training-reorg/12-summarize/), [2 AM](https://erinbecker.github.io/instructor-training-reorg/18-summarize/), [2PM](https://erinbecker.github.io/instructor-training-reorg/23-summarize/)) episodes have 'What have we learned?' as a question, but not a single one of these episodes actually provides a summary of what was covered in the previous episodes. 

As a simple and fairly easy to fix solution, I propose that we:
- [ ] delete this 'What have we learned?' question from all of the wrap-ups. 
- [ ] replace it with a 'What feedback do I have for the instructors?' question or something that more actually conveys that everyone of these wrap up calls for some sort of feedback in the form of minute-cards, one-up one-down, or a full length survey. 

As a larger and less easy to fix solution, I propose that we: 
- [ ] move all the feedback exercises (i.e. physical minute cards, [electronic minute cards](https://docs.google.com/forms/d/1Xc87sHqJsJ43X5KU_KORIfv_i4P_1hzSN-mWKd2TXmQ/edit), one-up-one-down, quite reflection, and end-of-workshop survey) to the instructor notes or to the end of the previous episode
- [ ] delete the AM wrap-up episodes entirely 
- [x] rename the Day 1 afternoon wrap-up section something like "Homework" 
- [x] rename the day 2 afternoon wrap-up section something like "Checkout Procedure"

Is anyone is favor of the easy or less easy solution?

**Comment by karenword** [comment]
The one thing I like about the wrap-ups is basically the idea of them. It's important to actually wrap up what you're doing, and when we move these things to the bottom of the curriculum that removes the emphasis and conceptual separation of that debriefing process. That being said, I agree that the homework and checkout content ought to be re-labeled, and that the feedback tools are best selected by the instructor as opposed to pre-arranged. So, maybe in favor of the less easy solution, with otherwise retained emphasis on the moved material?

**Comment by karenword** [comment]
Also in the same vein I suggest that we *add* a "what have we learned?" with a minute-card type activity in the new "second welcome" episode.

**Comment by raynamharris** [comment]
@ChristinaLK Can we close this issue?

**Comment by ChristinaLK** [comment]
yep.
