### ISSUE TITLE
Episode 4 typos and broken links

### ISSUE THREAD

**Issue by AnnaWilliford** [ErinBecker/instructor-training-reorg#58]
[earlier topic] link does not work

2. Experts are frequently .... (FIXME add references) ???

3. Densely-connected knowledge graphs also explains - graphs explain

4. ...as [Glass observed] - include the name? Robert Glass 

 in 1956, Miller estimated - include the name? George Miller

**Comment by AnnaWilliford** [comment]
I see that you only use the last names of authors throughout training materials. In this case, ignore my suggestions to include the first name. Although given that last names often repeat, using first+last name is a better way to identify the correct author.

**Comment by ErinBecker** [comment]
I agree that we should add first names throughout.

**Comment by ErinBecker** [comment]
Thanks @AnnaWilliford for these fixes. 

In the current version of the materials, it appears that the references to Glass and Miller have been removed (https://erinbecker.github.io/instructor-training-reorg/04-expertise/). Glass no longer appears in any episode, but Miller is not in episode 5. I added his first name there (https://github.com/ErinBecker/instructor-training-reorg/pull/183). 

The issue with the link is due to episode names/numbers changing. We're going to do a pass through all of the episodes at the very end to update these and fix the links. Thanks for having an eye out for this. 

I've added a note to the checklist to add a reference for expert-blind spot and expertise-reversal effect. Closing the issue here.
